
# Cassandra
spring.cassandra.contact-points=${CASSANDRA_HOST}
spring.cassandra.port=${CASSANDRA_PORT}
spring.cassandra.keyspace-name=${CASSANDRA_KEYSPACE_NAME}
spring.cassandra.local-datacenter=${CASSANDRA_LOCAL_DATA_CENTER}
spring.cassandra.ssl.enabled=true

spring.cassandra.request.timeout=5s
spring.cassandra.connection.connect-timeout=5s
spring.cassandra.connection.init-query-timeout=5s
spring.cassandra.compression=none

spring.cassandra.pool.heartbeat-interval=30s
spring.cassandra.pool.idle-timeout=60s

# MariaDB
spring.datasource.url=jdbc:mariadb://${MARIA_HOST}:${MARIA_PORT}/${MARIA_DB}
spring.datasource.username=${MARIA_USERNAME}
spring.datasource.password=${MARIA_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.jdbc.timezone=Asia/Seoul

# Redis
spring.data.redis.url=${REDIS_URL}
spring.data.redis.database=0
spring.data.redis.timeout=2000

# Eureka
eureka.client.service-url.defaultZone=http://${EUREKA_USERNAME}:${EUREKA_PASSWORD}@${EUREKA_DEFAULT_ZONE}/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.hostname=${EUREKA_USERNAME}
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${random.value}

logging.level.org.hibernate.SQL=INFO



